name: Biweekly Slipping Stories Report

on:
  schedule:
    - cron: '0 13 22,6 * *'  # Every other Thursday at 8:00 AM EST
  workflow_dispatch:

jobs:
  slipping-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install python-dotenv slack_sdk pandas matplotlib seaborn requests

      - name: Run Slipping Report Script
        env:
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          python slipping_stories_report.py

